### ISSUE TITLE
Custom sound effects are not played on coopdx version 1.0

### ISSUE THREAD

**Issue by SeymourSchlong** [wibblus/widdle-pets#1]
It just came out so I'd assume the fix may not be easily found, but custom sounds do not play on pets in sm64coop-dx 1.0
Sounds that are in vanilla (the bob-omb walk noise) play just fine.

**Comment by wibblus** [comment]
noted; i am working on a full rewrite of the audio sample system to be more optimized with new 1.0 features.
For a quick fix in the meantime, remove line **209** in main.lua (`audio_sample_destroy(bass)`), and the sounds should play.

**Comment by wibblus** [comment]
fixed in v1.2
